In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
p=a.ndim

In [5]:
p

2

In [6]:
a.itemsize

4

In [7]:
np.array([6,7,8])

array([6, 7, 8])

In [8]:
a.dtype

dtype('int32')

In [65]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.empty((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.empty((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [69]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [17]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [70]:
np.linspace(0,2*2.14,200)

array([0.        , 0.02150754, 0.04301508, 0.06452261, 0.08603015,
       0.10753769, 0.12904523, 0.15055276, 0.1720603 , 0.19356784,
       0.21507538, 0.23658291, 0.25809045, 0.27959799, 0.30110553,
       0.32261307, 0.3441206 , 0.36562814, 0.38713568, 0.40864322,
       0.43015075, 0.45165829, 0.47316583, 0.49467337, 0.5161809 ,
       0.53768844, 0.55919598, 0.58070352, 0.60221106, 0.62371859,
       0.64522613, 0.66673367, 0.68824121, 0.70974874, 0.73125628,
       0.75276382, 0.77427136, 0.79577889, 0.81728643, 0.83879397,
       0.86030151, 0.88180905, 0.90331658, 0.92482412, 0.94633166,
       0.9678392 , 0.98934673, 1.01085427, 1.03236181, 1.05386935,
       1.07537688, 1.09688442, 1.11839196, 1.1398995 , 1.16140704,
       1.18291457, 1.20442211, 1.22592965, 1.24743719, 1.26894472,
       1.29045226, 1.3119598 , 1.33346734, 1.35497487, 1.37648241,
       1.39798995, 1.41949749, 1.44100503, 1.46251256, 1.4840201 ,
       1.50552764, 1.52703518, 1.54854271, 1.57005025, 1.59155

In [71]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [21]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
np.arange(16).reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [23]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
np.array( [20,30,40,50] )

array([20, 30, 40, 50])

In [26]:
rg = np.random.default_rng(100)

In [27]:
print(rg)

Generator(PCG64)


In [28]:
c = np.arange(24).reshape(2,3,4)

In [29]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [73]:
c.sum()

676

In [72]:
c.sum(axis=0)

array([[100, 102, 104],
       [120, 124, 126]])

In [74]:
c.sum(axis=0)

array([[100, 102, 104],
       [120, 124, 126]])

In [33]:
c.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [34]:
c.min(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
c.cumsum(axis=1) 

array([[[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]],

       [[12, 13, 14, 15],
        [28, 30, 32, 34],
        [48, 51, 54, 57]]], dtype=int32)

In [36]:
c.cumsum(axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]], dtype=int32)

In [38]:
 np.arange(10)**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [39]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [40]:
np.fromfunction(f,(5,4),dtype=int)

NameError: name 'f' is not defined

In [41]:
def f(x,y):
...     return 10*x+y

In [42]:
np.fromfunction(f,(5,4),dtype=int)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [43]:
 c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
...                 [ 10, 12, 13]],
...                [[100,101,102],
...                 [110,112,113]]])

In [44]:
c.shape

(2, 2, 3)

In [45]:
np.floor(10*rg.random((3,4)))

array([[8., 5., 2., 0.],
       [9., 5., 7., 9.],
       [6., 1., 9., 2.]])

In [46]:
a.ravel()

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [75]:
c.resize((2,6))

In [52]:
np.sin(c)

array([[[ 0.        ,  0.84147098,  0.90929743],
        [-0.54402111, -0.53657292,  0.42016704]],

       [[-0.50636564,  0.45202579,  0.99482679],
        [-0.04424268, -0.8899956 , -0.09718191]]])

In [53]:
np.tan(c)

array([[[ 0.        ,  1.55740772, -2.18503986],
        [ 0.64836083, -0.63585993,  0.46302113]],

       [[-0.58721392,  0.5067526 ,  9.79298026],
        [ 0.04428604, -1.95187699, -0.09764409]]])

In [54]:
np.cos(c)

array([[[ 1.        ,  0.54030231, -0.41614684],
        [-0.83907153,  0.84385396,  0.90744678]],

       [[ 0.86231887,  0.89200487,  0.1015857 ],
        [-0.99902081,  0.4559691 ,  0.99526664]]])

In [59]:
np.arcsin(c)

<ipython-input-59-6473c7b6e743>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(c)


array([[[0.        , 1.57079633,        nan],
        [       nan,        nan,        nan]],

       [[       nan,        nan,        nan],
        [       nan,        nan,        nan]]])

In [61]:
np.rad2deg(c)

array([[[   0.        ,   57.29577951,  114.59155903],
        [ 572.95779513,  687.54935416,  744.84513367]],

       [[5729.57795131, 5786.87373082, 5844.16951033],
        [6302.53574644, 6417.12730547, 6474.42308498]]])

In [63]:
np.deg2rad(c)

array([[[0.        , 0.01745329, 0.03490659],
        [0.17453293, 0.20943951, 0.2268928 ]],

       [[1.74532925, 1.76278254, 1.78023584],
        [1.91986218, 1.95476876, 1.97222205]]])

In [64]:
np.arccos(c)

<ipython-input-64-387b33b2cf93>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(c)


array([[[1.57079633, 0.        ,        nan],
        [       nan,        nan,        nan]],

       [[       nan,        nan,        nan],
        [       nan,        nan,        nan]]])

In [78]:
np.tanh(c)

array([[0.        , 0.76159416, 0.96402758, 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]])

In [79]:
np.sinh(c)

array([[0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.10132329e+04,
        8.13773957e+04, 2.21206696e+05],
       [1.34405857e+43, 3.65352999e+43, 9.93132418e+43, 2.96048601e+47,
        2.18751972e+48, 5.94629511e+48]])

In [80]:
np.arcsinh(c)

array([[0.        , 0.88137359, 1.44363548, 2.99822295, 3.17978544,
        3.25957256],
       [5.29834237, 5.3082922 , 5.31814402, 5.39364821, 5.41166598,
        5.42055458]])

In [81]:
np.arccosh(c)

<ipython-input-81-c4c17a0481e7>:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(c)


array([[       nan, 0.        , 1.3169579 , 2.99322285, 3.17631318,
        3.25661395],
       [5.29829237, 5.30824319, 5.31809596, 5.39360688, 5.41162612,
        5.42051542]])

In [82]:
np.cosh(c)

array([[1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.10132329e+04,
        8.13773957e+04, 2.21206696e+05],
       [1.34405857e+43, 3.65352999e+43, 9.93132418e+43, 2.96048601e+47,
        2.18751972e+48, 5.94629511e+48]])

In [83]:
np.arctan(c)

array([[0.        , 0.78539816, 1.10714872, 1.47112767, 1.48765509,
        1.49402444],
       [1.56079666, 1.56089566, 1.56099272, 1.56170567, 1.56186799,
        1.561947  ]])

In [84]:
np.rint(c)

array([[  0.,   1.,   2.,  10.,  12.,  13.],
       [100., 101., 102., 110., 112., 113.]])

In [85]:
np.fix(c)

array([[  0.,   1.,   2.,  10.,  12.,  13.],
       [100., 101., 102., 110., 112., 113.]])

In [86]:
np.trunc(c)

array([[  0.,   1.,   2.,  10.,  12.,  13.],
       [100., 101., 102., 110., 112., 113.]])

In [87]:
np.ceil(c)

array([[  0.,   1.,   2.,  10.,  12.,  13.],
       [100., 101., 102., 110., 112., 113.]])

In [88]:
np.floor(c)

array([[  0.,   1.,   2.,  10.,  12.,  13.],
       [100., 101., 102., 110., 112., 113.]])

In [91]:
np.expm1(c)

array([[0.00000000e+00, 1.71828183e+00, 6.38905610e+00, 2.20254658e+04,
        1.62753791e+05, 4.42412392e+05],
       [2.68811714e+43, 7.30705998e+43, 1.98626484e+44, 5.92097203e+47,
        4.37503945e+48, 1.18925902e+49]])

In [92]:
np.exp2(c)

array([[1.00000000e+00, 2.00000000e+00, 4.00000000e+00, 1.02400000e+03,
        4.09600000e+03, 8.19200000e+03],
       [1.26765060e+30, 2.53530120e+30, 5.07060240e+30, 1.29807421e+33,
        5.19229686e+33, 1.03845937e+34]])

In [93]:
np.log10(c)

<ipython-input-93-76b2df9e070e>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(c)


array([[      -inf, 0.        , 0.30103   , 1.        , 1.07918125,
        1.11394335],
       [2.        , 2.00432137, 2.00860017, 2.04139269, 2.04921802,
        2.05307844]])

In [94]:
np.log2(c)

<ipython-input-94-cd5322e35d99>:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(c)


array([[      -inf, 0.        , 1.        , 3.32192809, 3.5849625 ,
        3.70043972],
       [6.64385619, 6.65821148, 6.67242534, 6.78135971, 6.80735492,
        6.82017896]])

In [98]:
np.sqrt(c)

array([[ 0.        ,  1.        ,  1.41421356,  3.16227766,  3.46410162,
         3.60555128],
       [10.        , 10.04987562, 10.09950494, 10.48808848, 10.58300524,
        10.63014581]])

In [101]:
np.nan_to_num(c)

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [102]:
np.absolute(c)

array([[  0,   1,   2,  10,  12,  13],
       [100, 101, 102, 110, 112, 113]])

In [103]:
np.add(9,16)

25

In [104]:
np.subtract(64,95)

-31

In [105]:
np.divide(444444,222234)

1.9998920057236966