# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.empty(10)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.60218627e-306,
       8.34441742e-308, 8.90104239e-307, 1.33511290e-306, 1.89146896e-307,
       1.60218491e-306, 0.00000000e+000])

3. Create a vector with values ranging from 10 to 49

In [6]:
array = np.arange(10,49)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [7]:
array.shape

(39,)

5. Print the type of the previous array in question 3

In [8]:
array.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [9]:
print(np.__version__)

1.19.2


7. Print the dimension of the array in question 3


In [11]:
array.ndim

1

8. Create a boolean array with all the True values

In [15]:
np.ones((1, 9), dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True]])

9. Create a two dimensional array




In [17]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [18]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [23]:
print(array)
array = array[::-1]
print('Reversed')
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Reversed
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
xx=np.empty(10)
xx[4] = 1
print(xx)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.60218627e-306
 1.00000000e+000 1.00000000e+000 1.33511290e-306 1.89146896e-307
 1.60218491e-306 0.00000000e+000]


13. Create a 3x3 identity matrix

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [31]:
arr = np.array([1, 2, 3, 4, 5])
convertedarray = arr.astype(np.float)
print(convertedarray)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [33]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
                      
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [34]:
arr1 = np.array([[1., 2., 3.],  [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [36]:
arr = np.arange(0,9)
condition = np.mod(arr, 2)!=0
np.extract(condition, arr)

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [39]:
arr = np.arange(0,9)
odd_values = (arr%2 == 1)
arr[odd_values] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [41]:
arr = np.arange(10)
arr[5] = arr[6] = arr[7] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [43]:
x = np.ones((9,9))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [47]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [108]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[::] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[64 64 64]
  [64 64 64]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [140]:
d = np.array([[1, 2, 3,9],[4, 6, 7,8]])
sliced = d[0,0:4]
print(sliced)

[1 2 3 9]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [141]:
d = np.array([[1, 2, 3,9],[4, 6, 7,8]])
sliced = d[0,1]
print(sliced)

2


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [143]:
d = np.array([[1, 2, 3,9],[4, 6, 7,8]])


[[1 2 3 9]
 [4 6 7 8]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [160]:
a= np.random.rand(10,10)
np.max(a)
np.min(a)


0.02567424602307966

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [162]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a == b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
cc=data[names != 'Will']
cc

array([[-0.28282985, -0.95974896, -1.42891486,  1.08937885],
       [ 0.13528233, -1.34587994, -0.35834459,  0.05595559],
       [ 2.43453375,  0.77664523, -0.60249283, -1.28573501],
       [-0.15507141,  1.30915775, -0.61674409, -0.57962839],
       [ 1.26746988,  0.80486217, -1.22676777,  0.1682662 ]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
cc= data[(names != 'Will') & (names != 'Joe')]
cc

array([[-0.02395412, -0.2819835 , -0.29197057, -0.16346055],
       [ 1.0586981 ,  0.16639489, -0.93947247,  0.3801171 ]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [128]:

# Input
arr = np.arange(1,16).reshape(5,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [12]:
aa=np.add(1,np.arange(16))
bb= aa.reshape(2,2,4)
bb

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [16]:
cc=np.swapaxes(bb,0,1)
cc

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [125]:
 a = np.array([0,0.2,0.1,5,2,6,7,3,8,9,10])
 a = np.sqrt(a)
 a[a<0.5]=0
 print(a)

[0.         0.         0.         2.23606798 1.41421356 2.44948974
 2.64575131 1.73205081 2.82842712 3.         3.16227766]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [103]:
a = np.random.randint(12)
b= np.random.randint(12)

np.random.rand(np.max(a),np.max(b))


array([[0.19406019, 0.66401955, 0.83314057, 0.49095768, 0.82103151],
       [0.58781429, 0.00270634, 0.73807668, 0.86588524, 0.49392613],
       [0.130418  , 0.98834451, 0.64095649, 0.47242972, 0.19617946]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [85]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [83]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.delete(sampleArray, 1, 1)
newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray,values = newColumn, obj = 1 , axis = 1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [54]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [50]:
x = np.random.random((5,5))
print(x)
print(x.sum())

[[0.74307577 0.98995458 0.5752777  0.92053175 0.3295116 ]
 [0.22637662 0.03165353 0.21322787 0.99363209 0.18500336]
 [0.93501591 0.87208013 0.24700255 0.66948361 0.96000555]
 [0.25079333 0.45996176 0.27765176 0.48695634 0.29636224]
 [0.10420242 0.32624946 0.54503914 0.1804695  0.80863346]]
12.628152044379778
